apiVersion: v1
kind: Service
metadata:
  labels:
    name: nbia
    prism: nbia
  name: nbia
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    name: nbia
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbia
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nbia
  template:
    metadata:
      labels:
        name: nbia
        prism: nbia
    spec:
      volumes:
      containers:
        - image: jrutecht/nbia:v1.1
          imagePullPolicy: Always
          name: nbia
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: nbia-search/
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: nbia-api/
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources: {}
      restartPolicy: Always
status: {}

