apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: posda-postgresql-pv-claim-auto
  labels:
      prism: posda
      posda: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
