apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: posda-cache-auto
  labels:
      prism: posda
      posda: cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
