apiVersion: v1
kind: Service
metadata:
  name: posdaweb
  labels:
      prism: posda
      posda: web
spec:
  type: NodePort
  ports:
  - port: 8080
    name: posdaweb
  selector:
    app: posdaweb

# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: "2022-05-04T23:48:29Z"
#   name: posdaweb
#   namespace: default
#   resourceVersion: "528285"
#   uid: 69013cf9-5f32-4e80-854c-ff1ea7e9daa6
# spec:
#   clusterIP: 10.110.162.142
#   clusterIPs:
#   - 10.110.162.142
#   externalTrafficPolicy: Cluster
#   internalTrafficPolicy: Cluster
#   ipFamilies:
#   - IPv4
#   ipFamilyPolicy: SingleStack
#   ports:
#   - nodePort: 31801
#     port: 8080
#     protocol: TCP
#     targetPort: 8080
#   selector:
#     app: posdaweb
#   sessionAffinity: None
#   type: NodePort
# status:
#   loadBalancer: {}




---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: posdaweb
  labels:
      prism: posda
      posda: web
spec:
  selector:
    matchLabels:
      app: posdaweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: posdaweb
        posda: posdaweb
    spec:
      containers:
      - image: tcia/posda_web:kubes
        name: posda-web
        imagePullPolicy: Always
        # envFrom:
        # - configMapRef:
        #     name: posda-map
        # - configMapRef:
        #     name: common
        # env:
        # - name: PGHOST
        #   value: "postgresql"
        # - name: PGUSER
        #   value: "postgres"
        # - name: PGPASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: postgresql-secret
        #       key: postgresql_root_password
        ports:
        - containerPort: 80
          name: posdaweb
