apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: facet-mongodb-pv
  labels:
    name: facet-mongodb-pv
    prism: facet-mongodb-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core-persistent-storage
  labels:
    name: core-persistent-storage
    prism: core-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
