kind: ConfigMap
apiVersion: v1
metadata:
  name: httpd-conf
data:
  httpd.conf: |
    ServerRoot "/etc/httpd"
    Listen 8080
    Listen 8443
    Include conf.modules.d/*.conf

    User apache
    Group root

    ServerAdmin root@localhost

    ServerName pathdb.127.0.0.1.nip.io

    <Directory />
        AllowOverride none
        Require all denied
    </Directory>

    DocumentRoot "/quip/web"
    <Directory "/quip/web">
        AllowOverride all
        Require all granted
        Options Indexes FollowSymLinks IncludesNOEXEC
        RewriteEngine On
        DirectoryIndex index.php index.htm index.html
        RewriteEngine on
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_URI} !=/favicon.ico
        RewriteRule ^ index.php [L]
    </Directory>

    <IfModule dir_module>
        DirectoryIndex index.html
    </IfModule>

    <Files ".ht*">
        Require all denied
    </Files>

    ErrorLog "/data/pathdb/logs/error_log"

    LogLevel warn
    <IfModule log_config_module>
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        LogFormat "%h %l %u %t \"%r\" %>s %b" common

        <IfModule logio_module>
          LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
        </IfModule>

        CustomLog "/data/pathdb/logs/access_log" combined
    </IfModule>

    <IfModule alias_module>
        ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"
    </IfModule>

    <Directory "/var/www/cgi-bin">
        AllowOverride None
        Options None
        Require all granted
    </Directory>

    <IfModule mime_module>
        TypesConfig /etc/mime.types
        AddType application/x-compress .Z
        AddType application/x-gzip .gz .tgz
        AddType text/html .shtml
        AddOutputFilter INCLUDES .shtml
    </IfModule>

    AddDefaultCharset UTF-8

    <IfModule mime_magic_module>
        MIMEMagicFile conf/magic
    </IfModule>

    EnableSendfile on

    IncludeOptional conf.d/*.conf

    <VirtualHost *:8080>
        SSLEngine off
        Options Indexes FollowSymLinks IncludesNOEXEC
        KeepAlive On
        DirectoryIndex index.php index.htm index.html
        ProxyPass /caMicroscope/img/ http://ca-security:4010/img/
        ProxyPassReverse /caMicroscope/img/ http://ca-security:4010/img/
        ProxyPass /caMicroscope/data/ http://ca-security:4010/data/
        ProxyPassReverse /caMicroscope/data/ http://ca-security:4010/data/
        ProxyRequests Off
        CustomLog "/data/pathdb/logs/access_log" combined
        ErrorLog "/data/pathdb/logs/error_log"
    </VirtualHost>

    <VirtualHost *:8443>
        Options Indexes FollowSymLinks IncludesNOEXEC
        RewriteEngine On
        KeepAlive On
        DirectoryIndex index.php index.htm index.html
        ProxyPass /caMicroscope/img/ http://ca-security:4010/img/
        ProxyPassReverse /caMicroscope/img/ http://ca-security:4010/img/
        ProxyPass /caMicroscope/data/ http://ca-security:4010/data/
        ProxyPassReverse /caMicroscope/data/ http://ca-security:4010/data/
        ProxyRequests Off
        CustomLog "/data/pathdb/logs/access_log" combined
        ErrorLog "/data/pathdb/logs/error_log"
    </VirtualHost>
