apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: iip
    prism: ca-iip
    pathdb: ca-iip
  name: ca-iip
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "443"
    port: 443
    targetPort: 8443
  selector:
    name: iip
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: iip
    prism: ca-iip
    pathdb: ca-iip
  name: iip
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iip
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: iip
        prism: ca-iip
        pathdb: ca-iip
    spec:
      containers:
      - image: camicroscope/iipimage:latest
        imagePullPolicy: Always
        name: ca-iip
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {}
        volumeMounts:
        - mountPath: /data/images
          name: data
          subPath: 'pathdb/files/wsi'
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
