apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    name: ca-mongodb
    prism: ca-mongodb
    pathdb: ca-mongodb
  name: ca-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
