apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: worker-high
  labels:
      prism: posda
      posda: worker-high
spec:
  selector:
    matchLabels:
      app: worker-high
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: worker-high
    spec:
      containers:
      - image: tcia/posda:kubes
        name: worker-high
        args: ["worker"]
        envFrom:
        - configMapRef:
            name: posda-map
        - configMapRef:
            name: common
        env:
        - name: POSDA_WORKER_PRIORITY
          value: "1"
        - name: POSDA_INTERNAL_API_URL
          value: "http://posdaweb:8080/papi"
        - name: PGHOST
          value: "posdapostgresql"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          valueFrom:
              secretKeyRef:
                  name: posda-postgresql-secret
                  key: postgresql_root_password
        # livenessProbe:
        #     httpGet:
        #         path: /
        #         port: 3000
        #     initialDelaySeconds: 30
        #     periodSeconds: 10
        #     timeoutSeconds: 5
        # readinessProbe:
        #     httpGet:
        #         path: /
        #         port: 3000
        #     initialDelaySeconds: 5
        #     periodSeconds: 2
        #     timeoutSeconds: 1
        volumeMounts:
        - name: posda-cache
          mountPath: /home/posda/cache
      volumes:
      - name: posda-cache
        persistentVolumeClaim:
          claimName: posda-cache-auto
